"""empty message

Revision ID: 3a5cfe0a734c
Revises: 271afbe680ca
Create Date: 2020-06-04 13:24:49.015619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5cfe0a734c'
down_revision = '271afbe680ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET completed= False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
